name: CI/CD

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'  

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run build

      - name: Build Docker image
        run: |
          docker build -t my-vue-app .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  
          password: ${{ secrets.DOCKER_PASSWORD }}  

      - name: Tag and Push Docker image
        run: |
          docker tag my-vue-app ${{ secrets.DOCKER_USERNAME }}/my-vue-app:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/my-vue-app:latest

      - name: Notify success
        run: echo "Docker image pushed successfully!"
